[project]
name = "venturalitica-sdk"
version = "0.1.0"
description = "Frictionless Governance for AI"
requires-python = ">=3.9"
dependencies = [
    "PyYAML>=6.0",
    "pandas>=2.0.0",
    "numpy>=1.24.0",
    "scikit-learn>=1.2.0",
    "cyclonedx-python-lib>=6.0.0",
    "typer>=0.9.0",
    "rich>=13.0.0",
    "streamlit>=1.30.0",
    "compliance-trestle>=3.4.0",
]

[project.scripts]
venturalitica = "venturalitica.cli:app"

[project.optional-dependencies]
metrics = [
    "fairlearn>=0.10.0",
]
torch = [
    "torch>=2.0.0",
]
full = [
    "venturalitica-sdk[metrics,torch]",
]
green = [
    "codecarbon>=2.3.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/venturalitica"]

[dependency-groups]
dev = [
    "clearml>=2.1.2",
    "mlflow>=3.1.4",
    "pytest>=8.4.2",
    "pytest-cov>=7.0.0",
    "pytest-mock>=3.15.1",
    "wandb>=0.24.0",
]
docs = [
    "mkdocs-llmstxt>=0.4.0",
    "mkdocs-material>=9.7.1",
    "mkdocstrings[python]>=0.30.1",
]
